package FrontEnd;

import Backend.Content;
import Backend.Session;
import Backend.User;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author vip comp
 */
public class ProfileScreen extends javax.swing.JFrame {
    private static Session S;

    /**
     * Creates new form ProfileScreen
     */
    public ProfileScreen(Session S) {
        initComponents();
        this.S = S;
        //For displaying profile photo, cover
             /*BufferedImage originalPhoto = (BufferedImage) S.getLoggedInUser().getProfilePhoto().getScaledInstance(profilePanel.getWidth(), profilePanel.getHeight(), Image.SCALE_SMOOTH);
             profileLabel.setIcon(new ImageIcon(originalPhoto));*/
        bioLabel.setText(S.getLoggedInUser().getBio());
        coverPhoto.setLayout(new java.awt.BorderLayout());
        String coverPhotoPath = S.getLoggedInUser().getCoverPhotoPath();
        if (coverPhotoPath != null) {
            ImageIcon coverIcon = new ImageIcon(coverPhotoPath);
            Image scaledCover = coverIcon.getImage().getScaledInstance(600, 200, Image.SCALE_SMOOTH);
            CoverHolder.setIcon(new ImageIcon(scaledCover));
            coverPhoto.add(CoverHolder);
        }

        profilePanel.setLayout(new java.awt.BorderLayout());
        String profilePhotoPath = S.getLoggedInUser().getProfilePhotoPath();
        if (profilePhotoPath != null) {
            ImageIcon profileIcon = new ImageIcon(profilePhotoPath);
            Image scaledProfile = profileIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            profileHolder.setIcon(new ImageIcon(scaledProfile));
            profilePanel.add(profileHolder);
        }
        // For displaying user's content
        ArrayList<Content> temp = S.getLoggedInUser().getContents();
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        for (Content i : temp) {
            JPanel contentPanel = new JPanel();
            contentPanel.setLayout(new java.awt.BorderLayout());
            JLabel textLabel = new JLabel(i.getText());
            contentPanel.add(textLabel, java.awt.BorderLayout.NORTH);
            if (i.getImage() != null) {
                ImageIcon imageIcon = new ImageIcon(i.getImage());
                JLabel imageLabel = new JLabel();
                Image scaledImage = imageIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                imageLabel.setIcon(new ImageIcon(scaledImage));
                contentPanel.add(imageLabel, java.awt.BorderLayout.CENTER);
            }
            JLabel dateLabel = new JLabel(i.getCreationTime().toLocalDate().toString());
            contentPanel.add(dateLabel, java.awt.BorderLayout.SOUTH);
            jPanel1.add(contentPanel);
        }
        //for displaying online/offline friends
        friendsLabel.setLayout(new javax.swing.BoxLayout(friendsLabel, javax.swing.BoxLayout.Y_AXIS));
        ArrayList<String> onFriends = new ArrayList<>();
        ArrayList<String> offFriends = new ArrayList<>();

        for (User i : S.getLoggedInUser().getFriends()) {
            if (i.getStatus().equals("Online")) {
                onFriends.add(i.getUsername());
            } else {
                offFriends.add(i.getUsername());
            }
        }

        JLabel on = new JLabel("Online Friends:");
        friendsLabel.add(on);

        for (String name : onFriends) {
            JLabel o = new JLabel(name);
            friendsLabel.add(o);
        }

        JLabel off = new JLabel("Offline Friends:");
        friendsLabel.add(off);

        for (String name : offFriends) {
            JLabel o = new JLabel(name);
            friendsLabel.add(o);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        profilephotoButton = new javax.swing.JButton();
        coverphotoButton = new javax.swing.JButton();
        changebioButton = new javax.swing.JButton();
        passwordButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        friendsLabel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        profileHolder = new javax.swing.JLabel();
        bioLabel = new javax.swing.JLabel();
        coverPhoto = new javax.swing.JPanel();
        CoverHolder = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Profile");

        jLabel1.setFont(new java.awt.Font("SF Pro Text", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Profile");

        profilephotoButton.setText("Change profile photo");
        profilephotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilephotoButtonActionPerformed(evt);
            }
        });

        coverphotoButton.setText("Change cover photo");
        coverphotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coverphotoButtonActionPerformed(evt);
            }
        });

        changebioButton.setText("change Bio");
        changebioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebioButtonActionPerformed(evt);
            }
        });

        passwordButton.setText("Edit Password");
        passwordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jLabel2.setText("My Posts");

        jLabel3.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jLabel3.setText("My Friends");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 247, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 391, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jPanel1);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout friendsLabelLayout = new javax.swing.GroupLayout(friendsLabel);
        friendsLabel.setLayout(friendsLabelLayout);
        friendsLabelLayout.setHorizontalGroup(
                friendsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        friendsLabelLayout.setVerticalGroup(
                friendsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 391, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(friendsLabel);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
                profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(profileHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                .addContainerGap())
        );
        profilePanelLayout.setVerticalGroup(
                profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(profilePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(profileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(profileHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                .addContainerGap())
        );

        bioLabel.setText("No bio.");

        javax.swing.GroupLayout coverPhotoLayout = new javax.swing.GroupLayout(coverPhoto);
        coverPhoto.setLayout(coverPhotoLayout);
        coverPhotoLayout.setHorizontalGroup(
                coverPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coverPhotoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CoverHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addContainerGap())
        );
        coverPhotoLayout.setVerticalGroup(
                coverPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(coverPhotoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CoverHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jScrollPane4)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(47, 47, 47)
                                                                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 63, Short.MAX_VALUE)
                                                                .addComponent(bioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(profilephotoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(changebioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(passwordButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(coverphotoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))))
                                                .addGap(0, 0, 0))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton5)
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(coverPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton5)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(coverPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(bioLabel)
                                                .addGap(37, 37, 37))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(profilephotoButton)
                                        .addComponent(coverphotoButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(changebioButton)
                                        .addComponent(passwordButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profilephotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilephotoButtonActionPerformed
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = f.showOpenDialog(null);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Image Files (jpg, png, gif, bmp)", "jpg", "png", "gif", "bmp");
        f.setFileFilter(filter);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = f.getSelectedFile();
            ImageIcon photoIcon = new ImageIcon(selectedFile.getAbsolutePath());
            BufferedImage scaledImage = (BufferedImage) photoIcon.getImage().getScaledInstance(profilePanel.getWidth(), profilePanel.getHeight(), Image.SCALE_SMOOTH);
            profileLabel.setIcon(new ImageIcon(scaledImage));
            // assign to user's
            S.getLoggedInUser().editProfilePhoto(scaledImage, selectedFile.toString());
        } else {
            JOptionPane.showMessageDialog(null, "No image Selected", "Note", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_profilephotoButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        NewsFeed NF = new NewsFeed(S);
        NF.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void coverphotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coverphotoButtonActionPerformed
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = f.showOpenDialog(null);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Image Files (jpg, png, gif, bmp)", "jpg", "png", "gif", "bmp");
        f.setFileFilter(filter);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = f.getSelectedFile();
            ImageIcon photoIcon = new ImageIcon(selectedFile.getAbsolutePath());
            Image scaledImage = photoIcon.getImage().getScaledInstance(profilePanel.getWidth(), profilePanel.getHeight(), Image.SCALE_SMOOTH);
            CoverHolder.setIcon(new ImageIcon(scaledImage));
            // assign to user's
        } else {
            JOptionPane.showMessageDialog(null, "No image Selected", "Note", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_coverphotoButtonActionPerformed

    private void changebioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebioButtonActionPerformed
        bioLabel.setText(JOptionPane.showInputDialog("Enter new Bio:"));
        User u = S.getLoggedInUser();
        u.editBio(bioLabel.getText());
        S.refresh();
    }//GEN-LAST:event_changebioButtonActionPerformed

    private void passwordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordButtonActionPerformed
        String newPass = JOptionPane.showInputDialog("Enter new password:");
        if (newPass.isBlank())
            JOptionPane.showMessageDialog(null, "Invalid Password", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            //assign to user's
        }
    }//GEN-LAST:event_passwordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileScreen(S).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoverHolder;
    private javax.swing.JLabel bioLabel;
    private javax.swing.JButton changebioButton;
    private javax.swing.JPanel coverPhoto;
    private javax.swing.JButton coverphotoButton;
    private javax.swing.JPanel friendsLabel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton passwordButton;
    private javax.swing.JLabel profileHolder;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton profilephotoButton;
    // End of variables declaration//GEN-END:variables
}
